### ISSUE TITLE
How does one make a file request?

### ISSUE THREAD

**Issue by meticulo3366** [CacheControl/hippie-swagger#11]
I need to upload files to a swagger api using a  hippie-swagger test as a form, i did not see any coverage.. what could I be missing..?

I noticed this in the code as well

```
/**
 * Asserts that request form data variables are in Swagger. Throws if not found.
 * @param  {Object} requestFormData - request form data(query string format) as a hash
 * @param  {Object} requestParams - hash of request parameters
 */
function handleFormData (requestFormData, specFormData) {
  for (var qsKey in requestFormData) {
    var found = false
    specFormData.forEach(function (formSpecParameter) {
      if (formSpecParameter.name === qsKey && formSpecParameter.type !== 'file') {
        found = true
      }
    })
    if (!found) {
      throwParamNotFound(qsKey, 'formData')
    }
  }
}
```

**Comment by CacheControl** [comment]
Hi @meticulo3366.  I did implement a test for this use-case, based on my reading of the swagger specification:

https://github.com/CacheControl/hippie-swagger/blob/9b2a4d2ee514e5c1ee0190cf76cc4eb23758e51e/test/parameters.test.js#L65

Does this approach work for your situation?
