### ISSUE TITLE
Unknown Format int64 ignore in schema

### ISSUE THREAD

**Issue by MrRoyce** [CacheControl/hippie-swagger#24]
My swagger file has
```javascript
"id": {
  "type": "integer",
  "format": "int64"
}
```
I get the following error when running the test (looks like its coming from the ajv library):

![hippie_swagger_nt64_error](https://user-images.githubusercontent.com/252359/28244928-5d974c72-69c7-11e7-9b7a-dd6f5e4ff921.png)

Any ideas on how to get this to validate?

Thanks

**Comment by CacheControl** [comment]
@MrRoyce As a short term fix, try removing `"format": "int64"` from your swagger definition.   

In terms of a long term fix, it looks like we need to whitelist the "int32"/ "int64" swagger formats in the [ajv options](https://github.com/epoberezkin/ajv/blob/97413655e48e466417a55ea382f18e96b123e2bf/README.md#validation-and-reporting-options), which hippie-swagger uses under the hood.  If you feel like taking a crack at it I'd certainly accept a PR 😄

**Comment by MrRoyce** [comment]
I think the ajv assignment in lib/parameters/js should be:

`var ajv = require('ajv')({coerceTypes: ['number', 'boolean'], unknownFormats: ['int32', 'int64']})`

But for a PR, I'm struggling a bit with a test for  the case with int32/int34 and also a case where someone makes a typo like int23.

**Comment by CacheControl** [comment]
@MrRoyce ok, thanks.  I may have some free time this week to implement this.
