### ISSUE TITLE
How to run the example

### ISSUE THREAD

**Issue by lcofre** [CacheControl/hippie-swagger#25]
Sorry for this basic question. How do you run the example?

Thanks for helping this newbie.

**Comment by CacheControl** [comment]
@lcofre there's a comment at the top, though I realize now it's not super obvious and should probably be promoted to the README!

https://github.com/CacheControl/hippie-swagger/blob/master/example/index.js#L6

**Comment by lcofre** [comment]
I just realised too! Thanks for your readiness!
