### ISSUE TITLE
swagger = require('dereferenced-swagger-file'); this module is not present in node

### ISSUE THREAD

**Issue by tarunairvm** [CacheControl/hippie-swagger#31]

**Comment by CacheControl** [comment]
@tarunairvm that `require()` line is supposed to be your dereferenced swagger file, please see the [example](https://github.com/CacheControl/hippie-swagger/blob/master/example/index.js#L21) for how to do this.  I'll add a note to the README to make this more clear.  Apologies for the confusion.
