### ISSUE TITLE
Swagger schema required using OpenAPI 3.0

### ISSUE THREAD

**Issue by gt-novelt** [CacheControl/hippie-swagger#34]
According to the specs the `swagger` key has been replaced by `openapi`
https://swagger.io/specification/#schema

---
The line below is causing the issue.
https://github.com/CacheControl/hippie-swagger/blob/fd60e3416bf89d19176c138820b7b2f231992184/lib/validate-swagger.js#L24

One way of fixing this (not the most elegant) could be
```js
function isSwagger (obj) {
  var requiredKeys = [['openapi', 'swagger'], 'info', 'paths']
  return requiredKeys.every(function (key) {
    if (Array.isArray(key)) {
      return key.some(function (alias) {
        return obj.hasOwnProperty(alias)
      })
    }
    return obj.hasOwnProperty(key)
  })
}
```
I went ahead and proposed a pull request of that very changes #35

**Comment by CacheControl** [comment]
Added to roadmap under open api 3.0 support
