### ISSUE TITLE
Test a deployed/production API

### ISSUE THREAD

**Issue by poliveira89** [CacheControl/hippie-swagger#7]
Seems that this library needs and object of the server/application to be passed to `hippie(...)` function.

I'm able to use `hippie-swagger` to create automated tests for an remote deployed API? If I can, how I can I do it?

Because as far I have analyzed the `app` argument is highly coupled in to the code:
https://github.com/CacheControl/hippie-swagger/blob/master/lib/hippie-swagger.js#L24

**Comment by CacheControl** [comment]
@poliveira89 Great point!  Thank you for bringing this to my attention.  I generally don't use the remote api testing capabilities of hippie, and I'd completely forgotten about the feature.

I've published **1.3.0**, which allows the 'app' argument of the constructor to be optional.  Documentation has been added to the [README](https://github.com/CacheControl/hippie-swagger#constructor-object-swagger-object-options)

Let me know if you run into any issues.  Cheers!
